# Generated by Django 5.1.1 on 2024-09-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_ss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userservice",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
