# Generated by Django 5.1.1 on 2024-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_ss", "0002_userservice_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userservice",
            name="senha",
        ),
        migrations.AlterField(
            model_name="userservice",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
