# Generated by Django 5.1.1 on 2024-09-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_ss", "0003_remove_userservice_senha_alter_userservice_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True)),
                ("atualizacao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome_empresa", models.CharField(max_length=50)),
                ("cnpj_empresa", models.CharField(max_length=25)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True)),
                ("atualizacao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome_servico", models.CharField(max_length=100)),
                ("tipo_servico", models.CharField(max_length=50)),
                ("codigo_servico", models.CharField(max_length=50, unique=True)),
                ("data_emissao_servico", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos",
                        to="api_ss.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "unique_together": {("tipo_servico", "empresa")},
            },
        ),
        migrations.DeleteModel(
            name="UserService",
        ),
    ]
